apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: mmk
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "mmk"
    description: prova
    properties:
      kdtable:
        title: prova
        description: prova
        type: object
  dependencies:
  - "camel:core"
  - "camel:kamelet"
  - "github:kiegroup.yard/yard-kdtable/camelk-SNAPSHOT"
  template:
    beans:
      - name: mmbean
        type: '#class:org.drools.yard.kdtable.KdtableProcessor'
        properties:
          kdtable: '{{kdtable}}'
    from:
      uri: "kamelet:source"
      steps:
      - process:
          ref: '{{mmbean}}'
      - to: "log:info"
