apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: mmk
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "mmk"
    description: prova
    properties:
      milliseconds:
        title: Milliseconds
        description: The number of milliseconds of delay
        type: integer
        example: 1000
      yard.kdtable:
        title: prova
        description: prova
        type: object
  dependencies:
  - "camel:core"
  - "camel:kamelet"
  - "github:kiegroup/yard/kamelet"
  template:
    beans:
      - name: myp
        type: org.drools.yard.kdtable.KdtableProcessor
    from:
      uri: "kamelet:source"
      steps:
      - process:
          ref: myp
      - to: "log:info"
