apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: timer-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: timer-source
    properties:
      message: hello world
      period: 5000
  steps:
    - ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1alpha1
        name: kdtable
      properties:
        # set as block string (undesirable, but the only available current workaround)
        kdtable: |
          type: DecisionTable
          inputs: ['Age', 'Previous incidents?']
          rules:
          - when: ['<21', false]
            then: 800
          - when: ['<21', true]
            then: 1000
          - when: ['>=21', false]
            then: 500
          - when: ['>=21', true]
            then: 600
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
