apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: timer-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: timer-source
    properties:
      message: hello world
      period: 5000
  steps:
    - ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1alpha1
        name: mmk
      properties:
        kdtable:
          type: DecisionTable
          inputs: ['Violation.type', 'Violation.Actual Speed - Violation.Speed Limit']
          outputComponents: ['Amount', 'Points']
          rules:
            - ['="speed"', '[10..30)', 500, 3]
            - ['="speed"', '>= 30', 1000, 7]
            - ['="parking"', '-', 100, 1]
            - ['="driving under the influence"', '-', 1000, 5]
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: mmk
    properties:
      kdtable: prova this value was set inside KameletBinding where the kamelet is a sink
