apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: timer-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: timer-source
    properties:
      message: hello world
      period: 5000
  steps:
    - ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1alpha1
        name: mmk
      properties:
        kdtable: prova this value was set inside KameletBinding
        kdtable2: this is an hack
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: mmk
    properties:
      kdtable: prova this value was set inside KameletBinding
      kdtable2: this is an hack
